spring.datasource.url=jdbc:postgresql://localhost:5432/freshtouch_db
spring.datasource.username=postgres
spring.datasource.password=davis
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
